version: "3.0"

version: "3.0"

services:
  angular-service:
    container_name: webapp-service-prod
    build: ./tqs_webapp
    command: ng serve --prod --host 0.0.0.0 --port 4200 --disable-host-check
    networks:
      - webapp_test
    env_file: ./deployment/.env
    ports:
        - 4200:4200

networks:
  webapp_test:
