name: Continuous Delivery 4 Deployment Environment (private)

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v1
      - run: sh prod.sh