name: Continuous Delivery 4 Test Environment (private)

on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v1
      - run: sh test.sh